/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IniAlert {
        "dismissible": boolean;
        "headerTitle": string;
        "variant": "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    interface IniBadge {
        "variant": "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    interface IniButton {
        "disabled": boolean;
        "extraClass": string;
        "outline": boolean;
        "size": "small" | "medium" | "large";
        "variant": "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    interface IniCard {
        "headerTitle": string;
    }
    /**
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface IniDatePicker {
        "dateFormat": string;
        "disabled": boolean;
        "helpText": string;
        "label": string;
        "name": string;
        "placeholder": string;
        "value": string;
    }
    /**
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface IniDateRangePicker {
        "dateFormat": string;
        "disabled": boolean;
        "endName": string;
        "endPlaceholder": string;
        "endValue": string;
        "helpText": string;
        "label": string;
        "startName": string;
        "startPlaceholder": string;
        "startValue": string;
    }
    interface IniDropdown {
        "disabled": boolean;
        "label": string;
        "outline": boolean;
        "placement": "top" | "bottom" | "right" | "left";
        "size": "small" | "medium" | "large";
    }
    interface IniInput {
        "disabled": boolean;
        "getInputRef": () => Promise<HTMLElement>;
        /**
          * The id value for input and label attributes
         */
        "groupId": string;
        "helpText": string;
        "inline": boolean;
        "label": string;
        "name": string;
        "placeholder": string;
        "prefixIcon": string;
        "prefixText": string;
        "size": "small" | "medium" | "large";
        "suffixIcon": string;
        "suffixText": string;
        "type": "text" | "password" | "email" | "number" | "search" | "tel" | "url" | "color" | "file" | "textarea";
        "value": string;
    }
    interface IniModal {
        "centerY": boolean;
        "closeLabel": string;
        "headerTitle": string;
        "open": boolean;
    }
    /**
     * Select control
     */
    interface IniSelect {
        "allowEmpty": boolean;
        "disabled": boolean;
        "multiple": boolean;
        "name": string;
        "placeholder": string;
    }
    interface IniTooltip {
        "placement": "top" | "bottom" | "right" | "left";
        "titleContent": string;
    }
}
export interface IniButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIniButtonElement;
}
declare global {
    interface HTMLIniAlertElement extends Components.IniAlert, HTMLStencilElement {
    }
    var HTMLIniAlertElement: {
        prototype: HTMLIniAlertElement;
        new (): HTMLIniAlertElement;
    };
    interface HTMLIniBadgeElement extends Components.IniBadge, HTMLStencilElement {
    }
    var HTMLIniBadgeElement: {
        prototype: HTMLIniBadgeElement;
        new (): HTMLIniBadgeElement;
    };
    interface HTMLIniButtonElement extends Components.IniButton, HTMLStencilElement {
    }
    var HTMLIniButtonElement: {
        prototype: HTMLIniButtonElement;
        new (): HTMLIniButtonElement;
    };
    interface HTMLIniCardElement extends Components.IniCard, HTMLStencilElement {
    }
    var HTMLIniCardElement: {
        prototype: HTMLIniCardElement;
        new (): HTMLIniCardElement;
    };
    /**
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface HTMLIniDatePickerElement extends Components.IniDatePicker, HTMLStencilElement {
    }
    var HTMLIniDatePickerElement: {
        prototype: HTMLIniDatePickerElement;
        new (): HTMLIniDatePickerElement;
    };
    /**
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface HTMLIniDateRangePickerElement extends Components.IniDateRangePicker, HTMLStencilElement {
    }
    var HTMLIniDateRangePickerElement: {
        prototype: HTMLIniDateRangePickerElement;
        new (): HTMLIniDateRangePickerElement;
    };
    interface HTMLIniDropdownElement extends Components.IniDropdown, HTMLStencilElement {
    }
    var HTMLIniDropdownElement: {
        prototype: HTMLIniDropdownElement;
        new (): HTMLIniDropdownElement;
    };
    interface HTMLIniInputElement extends Components.IniInput, HTMLStencilElement {
    }
    var HTMLIniInputElement: {
        prototype: HTMLIniInputElement;
        new (): HTMLIniInputElement;
    };
    interface HTMLIniModalElement extends Components.IniModal, HTMLStencilElement {
    }
    var HTMLIniModalElement: {
        prototype: HTMLIniModalElement;
        new (): HTMLIniModalElement;
    };
    /**
     * Select control
     */
    interface HTMLIniSelectElement extends Components.IniSelect, HTMLStencilElement {
    }
    var HTMLIniSelectElement: {
        prototype: HTMLIniSelectElement;
        new (): HTMLIniSelectElement;
    };
    interface HTMLIniTooltipElement extends Components.IniTooltip, HTMLStencilElement {
    }
    var HTMLIniTooltipElement: {
        prototype: HTMLIniTooltipElement;
        new (): HTMLIniTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "ini-alert": HTMLIniAlertElement;
        "ini-badge": HTMLIniBadgeElement;
        "ini-button": HTMLIniButtonElement;
        "ini-card": HTMLIniCardElement;
        "ini-date-picker": HTMLIniDatePickerElement;
        "ini-date-range-picker": HTMLIniDateRangePickerElement;
        "ini-dropdown": HTMLIniDropdownElement;
        "ini-input": HTMLIniInputElement;
        "ini-modal": HTMLIniModalElement;
        "ini-select": HTMLIniSelectElement;
        "ini-tooltip": HTMLIniTooltipElement;
    }
}
declare namespace LocalJSX {
    interface IniAlert {
        "dismissible"?: boolean;
        "headerTitle"?: string;
        "variant"?: "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    interface IniBadge {
        "variant"?: "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    interface IniButton {
        "disabled"?: boolean;
        "extraClass"?: string;
        "onIniClick"?: (event: IniButtonCustomEvent<any>) => void;
        "outline"?: boolean;
        "size"?: "small" | "medium" | "large";
        "variant"?: "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    interface IniCard {
        "headerTitle"?: string;
    }
    /**
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface IniDatePicker {
        "dateFormat"?: string;
        "disabled"?: boolean;
        "helpText"?: string;
        "label"?: string;
        "name"?: string;
        "placeholder"?: string;
        "value"?: string;
    }
    /**
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface IniDateRangePicker {
        "dateFormat"?: string;
        "disabled"?: boolean;
        "endName"?: string;
        "endPlaceholder"?: string;
        "endValue"?: string;
        "helpText"?: string;
        "label"?: string;
        "startName"?: string;
        "startPlaceholder"?: string;
        "startValue"?: string;
    }
    interface IniDropdown {
        "disabled"?: boolean;
        "label"?: string;
        "outline"?: boolean;
        "placement"?: "top" | "bottom" | "right" | "left";
        "size"?: "small" | "medium" | "large";
    }
    interface IniInput {
        "disabled"?: boolean;
        /**
          * The id value for input and label attributes
         */
        "groupId"?: string;
        "helpText"?: string;
        "inline"?: boolean;
        "label"?: string;
        "name"?: string;
        "placeholder"?: string;
        "prefixIcon"?: string;
        "prefixText"?: string;
        "size"?: "small" | "medium" | "large";
        "suffixIcon"?: string;
        "suffixText"?: string;
        "type"?: "text" | "password" | "email" | "number" | "search" | "tel" | "url" | "color" | "file" | "textarea";
        "value"?: string;
    }
    interface IniModal {
        "centerY"?: boolean;
        "closeLabel"?: string;
        "headerTitle"?: string;
        "open"?: boolean;
    }
    /**
     * Select control
     */
    interface IniSelect {
        "allowEmpty"?: boolean;
        "disabled"?: boolean;
        "multiple"?: boolean;
        "name"?: string;
        "placeholder"?: string;
    }
    interface IniTooltip {
        "placement"?: "top" | "bottom" | "right" | "left";
        "titleContent"?: string;
    }
    interface IntrinsicElements {
        "ini-alert": IniAlert;
        "ini-badge": IniBadge;
        "ini-button": IniButton;
        "ini-card": IniCard;
        "ini-date-picker": IniDatePicker;
        "ini-date-range-picker": IniDateRangePicker;
        "ini-dropdown": IniDropdown;
        "ini-input": IniInput;
        "ini-modal": IniModal;
        "ini-select": IniSelect;
        "ini-tooltip": IniTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ini-alert": LocalJSX.IniAlert & JSXBase.HTMLAttributes<HTMLIniAlertElement>;
            "ini-badge": LocalJSX.IniBadge & JSXBase.HTMLAttributes<HTMLIniBadgeElement>;
            "ini-button": LocalJSX.IniButton & JSXBase.HTMLAttributes<HTMLIniButtonElement>;
            "ini-card": LocalJSX.IniCard & JSXBase.HTMLAttributes<HTMLIniCardElement>;
            /**
             * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
             */
            "ini-date-picker": LocalJSX.IniDatePicker & JSXBase.HTMLAttributes<HTMLIniDatePickerElement>;
            /**
             * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
             */
            "ini-date-range-picker": LocalJSX.IniDateRangePicker & JSXBase.HTMLAttributes<HTMLIniDateRangePickerElement>;
            "ini-dropdown": LocalJSX.IniDropdown & JSXBase.HTMLAttributes<HTMLIniDropdownElement>;
            "ini-input": LocalJSX.IniInput & JSXBase.HTMLAttributes<HTMLIniInputElement>;
            "ini-modal": LocalJSX.IniModal & JSXBase.HTMLAttributes<HTMLIniModalElement>;
            /**
             * Select control
             */
            "ini-select": LocalJSX.IniSelect & JSXBase.HTMLAttributes<HTMLIniSelectElement>;
            "ini-tooltip": LocalJSX.IniTooltip & JSXBase.HTMLAttributes<HTMLIniTooltipElement>;
        }
    }
}
