/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * The Alert component serves as a dynamic container for conveying vital notifications and messages.
     * Depending on the context, alerts can adopt various types such as Primary, Danger, Success, Warning, and other relevant variants. Each type visually signifies its importance and relevance.
     * Additionally, to enhance clarity and emphasis, alerts can be complemented with a title. For users desiring an uncluttered interface,
     * the alerts also offer a dismissible feature, enabling them to close the message after acknowledgment. Through all its configurations, the Alert component ensures that key communications remain prominent and clear.
     */
    interface IniAlert {
        /**
          * Allows you to hide the alert if the close button is clicked
         */
        "dismissible": boolean;
        /**
          * (optional) The title of the alert that accompanies the content
         */
        "headerTitle": string;
        /**
          * Context of the alert, if it is an error message: `danger`, an action which is successful: `success` ...
         */
        "variant": "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    /**
     * The Badge component is a compact yet powerful means of showcasing status, highlighting states, or drawing attention to specific data points.
     * With its minimalist design, it effortlessly integrates into various UI contexts, making it a go-to for concise visual feedback
     */
    interface IniBadge {
        /**
          * Variant color of badge
         */
        "variant": "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    /**
     * The Button component stands as an interactive gateway, inviting users to take action, navigate, or submit.
     * With its versatile design, it can signal importance, set priorities, or provide navigational cues.
     * Whether beckoning a user to 'Learn More', confirming a choice with 'Submit', or pausing a task with 'Cancel', the Button ensures every interaction is clear and intentional.
     */
    interface IniButton {
        "disabled": boolean;
        "extraClass": string;
        "outline": boolean;
        "size": "small" | "medium" | "large";
        "variant": "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    /**
     * The Card component acts as a versatile container, framing content with a clear visual boundary. Whether showcasing snippets of text,
     * hosting other UI components, or spotlighting information with an optional title, the Card offers a neat and structured presentation.
     * It effectively organizes and emphasizes content, ensuring that information stands out in an engaging manner.
     */
    interface IniCard {
        "headerTitle": string;
    }
    /**
     * The Date Picker component simplifies the task of selecting dates by providing a user-friendly interface.
     * Whether setting an appointment, scheduling an event, or marking a milestone, it seamlessly integrates into forms and interfaces.
     * With intuitive navigation through days, months, and years, the Date Picker ensures that capturing a specific date or date range is both precise and effortless.
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface IniDatePicker {
        "dateFormat": string;
        "disabled": boolean;
        "helpText": string;
        "label": string;
        "name": string;
        "placeholder": string;
        "value": string;
    }
    /**
     * The Date Range Picker component streamlines the process of selecting a span of dates. Ideal for defining periods such as booking intervals,
     * financial quarters, or event durations, it offers an intuitive interface to capture both start and end dates. Its user-centric design ensures
     * that selecting consecutive days or disparate intervals is straightforward, providing clarity and precision in every date range selection.
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface IniDateRangePicker {
        "dateFormat": string;
        "disabled": boolean;
        "endName": string;
        "endPlaceholder": string;
        "endValue": string;
        "helpText": string;
        "label": string;
        "startName": string;
        "startPlaceholder": string;
        "startValue": string;
    }
    /**
     * The Dropdown component offers a compact way to present multiple options without overwhelming the interface.
     * By clicking or hovering, users can unveil a list of choices, making selections both space-efficient and user-friendly.
     * Whether used for navigation, action lists, or form inputs, the Dropdown ensures a smooth experience, guiding users through their options with elegance and simplicity.
     * This component use the Popper library : https://popper.js.org/docs/v2/
     */
    interface IniDropdown {
        "disabled": boolean;
        "label": string;
        "outline": boolean;
        "placement": "top" | "bottom" | "right" | "left";
        "size": "small" | "medium" | "large";
    }
    /**
     * Form Input components are the essential touchpoints of user data entry. From simple text fields capturing names to specialized inputs like emails or color pickers,
     * they transform user interactions into actionable data. Designed for clarity and ease of use, these components ensure that users effortlessly provide information,
     * whether its personal details, preferences, or any specific input. Every interaction is optimized for accuracy, ensuring data integrity across varied input types.
     */
    interface IniInput {
        "disabled": boolean;
        "getInputRef": () => Promise<HTMLElement>;
        /**
          * The id value for input and label attributes
         */
        "groupId": string;
        "helpText": string;
        "inline": boolean;
        "label": string;
        "name": string;
        "placeholder": string;
        "prefixIcon": string;
        "prefixText": string;
        "size": "small" | "medium" | "large";
        "suffixIcon": string;
        "suffixText": string;
        "type": "text" | "password" | "email" | "number" | "search" | "tel" | "url" | "color" | "file" | "textarea";
        "value": string;
    }
    /**
     * The Modal component emerges as a focused overlay, capturing users' full attention to deliver essential content or actions.
     * Whether presenting vital information, confirming user decisions, or offering supplemental details, the Modal provides an immersive environment, momentarily separating users from the main interface.
     * Its distinct presence ensures that the information or actions within are both central and prioritized, facilitating focused interactions.
     */
    interface IniModal {
        "centerY": boolean;
        "closeLabel": string;
        "headerTitle": string;
        "open": boolean;
    }
    /**
     * The Select control offers an intuitive way to present a list of options to users. It allows for easy single or multiple selections from a dropdown menu.
     * Additionally, some select controls provide the ability to search or type in text, offering users an even more streamlined experience.
     * Whether you're choosing from a predefined list or inputting new information, the Select control is designed to handle both with efficiency.
     * Plus, with built-in functions for adding or removing options, it ensures a dynamic user interaction that adapts to various needs.
     * This component use TomSelect library : https://tom-select.js.org/docs/
     */
    interface IniSelect {
        "allowEmpty": boolean;
        "disabled": boolean;
        "multiple": boolean;
        "name": string;
        "placeholder": string;
        /**
          * Pass the values selected by default (for multiple values must be used a delimiter between the values example: `apple,grape,orange`)
         */
        "selected": string;
    }
    /**
     * The Tooltip component acts as a brief informational aide, offering users additional context or guidance when they hover or focus on an element.
     * Subtle yet informative, it unveils insights without disrupting the user flow. Whether elucidating an icon's function,
     * providing supplementary data, or explaining a term, the Tooltip ensures clarity is just a hover away.
     * > The content which must display the tooltip when hovering must be wrapped by `<ini-tooltip>`, can be text, button, any other elements
     * This component use the Popper library : https://popper.js.org/docs/v2/
     */
    interface IniTooltip {
        /**
          * Where should the tooltip be displayed by bringing the element, if the tooltip leaves the parent container, then it will be replaced automatically
         */
        "placement": "top" | "bottom" | "right" | "left";
        /**
          * The content to display in the tooltip when hovering
         */
        "titleContent": string;
    }
}
export interface IniButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIniButtonElement;
}
declare global {
    /**
     * The Alert component serves as a dynamic container for conveying vital notifications and messages.
     * Depending on the context, alerts can adopt various types such as Primary, Danger, Success, Warning, and other relevant variants. Each type visually signifies its importance and relevance.
     * Additionally, to enhance clarity and emphasis, alerts can be complemented with a title. For users desiring an uncluttered interface,
     * the alerts also offer a dismissible feature, enabling them to close the message after acknowledgment. Through all its configurations, the Alert component ensures that key communications remain prominent and clear.
     */
    interface HTMLIniAlertElement extends Components.IniAlert, HTMLStencilElement {
    }
    var HTMLIniAlertElement: {
        prototype: HTMLIniAlertElement;
        new (): HTMLIniAlertElement;
    };
    /**
     * The Badge component is a compact yet powerful means of showcasing status, highlighting states, or drawing attention to specific data points.
     * With its minimalist design, it effortlessly integrates into various UI contexts, making it a go-to for concise visual feedback
     */
    interface HTMLIniBadgeElement extends Components.IniBadge, HTMLStencilElement {
    }
    var HTMLIniBadgeElement: {
        prototype: HTMLIniBadgeElement;
        new (): HTMLIniBadgeElement;
    };
    /**
     * The Button component stands as an interactive gateway, inviting users to take action, navigate, or submit.
     * With its versatile design, it can signal importance, set priorities, or provide navigational cues.
     * Whether beckoning a user to 'Learn More', confirming a choice with 'Submit', or pausing a task with 'Cancel', the Button ensures every interaction is clear and intentional.
     */
    interface HTMLIniButtonElement extends Components.IniButton, HTMLStencilElement {
    }
    var HTMLIniButtonElement: {
        prototype: HTMLIniButtonElement;
        new (): HTMLIniButtonElement;
    };
    /**
     * The Card component acts as a versatile container, framing content with a clear visual boundary. Whether showcasing snippets of text,
     * hosting other UI components, or spotlighting information with an optional title, the Card offers a neat and structured presentation.
     * It effectively organizes and emphasizes content, ensuring that information stands out in an engaging manner.
     */
    interface HTMLIniCardElement extends Components.IniCard, HTMLStencilElement {
    }
    var HTMLIniCardElement: {
        prototype: HTMLIniCardElement;
        new (): HTMLIniCardElement;
    };
    /**
     * The Date Picker component simplifies the task of selecting dates by providing a user-friendly interface.
     * Whether setting an appointment, scheduling an event, or marking a milestone, it seamlessly integrates into forms and interfaces.
     * With intuitive navigation through days, months, and years, the Date Picker ensures that capturing a specific date or date range is both precise and effortless.
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface HTMLIniDatePickerElement extends Components.IniDatePicker, HTMLStencilElement {
    }
    var HTMLIniDatePickerElement: {
        prototype: HTMLIniDatePickerElement;
        new (): HTMLIniDatePickerElement;
    };
    /**
     * The Date Range Picker component streamlines the process of selecting a span of dates. Ideal for defining periods such as booking intervals,
     * financial quarters, or event durations, it offers an intuitive interface to capture both start and end dates. Its user-centric design ensures
     * that selecting consecutive days or disparate intervals is straightforward, providing clarity and precision in every date range selection.
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface HTMLIniDateRangePickerElement extends Components.IniDateRangePicker, HTMLStencilElement {
    }
    var HTMLIniDateRangePickerElement: {
        prototype: HTMLIniDateRangePickerElement;
        new (): HTMLIniDateRangePickerElement;
    };
    /**
     * The Dropdown component offers a compact way to present multiple options without overwhelming the interface.
     * By clicking or hovering, users can unveil a list of choices, making selections both space-efficient and user-friendly.
     * Whether used for navigation, action lists, or form inputs, the Dropdown ensures a smooth experience, guiding users through their options with elegance and simplicity.
     * This component use the Popper library : https://popper.js.org/docs/v2/
     */
    interface HTMLIniDropdownElement extends Components.IniDropdown, HTMLStencilElement {
    }
    var HTMLIniDropdownElement: {
        prototype: HTMLIniDropdownElement;
        new (): HTMLIniDropdownElement;
    };
    /**
     * Form Input components are the essential touchpoints of user data entry. From simple text fields capturing names to specialized inputs like emails or color pickers,
     * they transform user interactions into actionable data. Designed for clarity and ease of use, these components ensure that users effortlessly provide information,
     * whether its personal details, preferences, or any specific input. Every interaction is optimized for accuracy, ensuring data integrity across varied input types.
     */
    interface HTMLIniInputElement extends Components.IniInput, HTMLStencilElement {
    }
    var HTMLIniInputElement: {
        prototype: HTMLIniInputElement;
        new (): HTMLIniInputElement;
    };
    /**
     * The Modal component emerges as a focused overlay, capturing users' full attention to deliver essential content or actions.
     * Whether presenting vital information, confirming user decisions, or offering supplemental details, the Modal provides an immersive environment, momentarily separating users from the main interface.
     * Its distinct presence ensures that the information or actions within are both central and prioritized, facilitating focused interactions.
     */
    interface HTMLIniModalElement extends Components.IniModal, HTMLStencilElement {
    }
    var HTMLIniModalElement: {
        prototype: HTMLIniModalElement;
        new (): HTMLIniModalElement;
    };
    /**
     * The Select control offers an intuitive way to present a list of options to users. It allows for easy single or multiple selections from a dropdown menu.
     * Additionally, some select controls provide the ability to search or type in text, offering users an even more streamlined experience.
     * Whether you're choosing from a predefined list or inputting new information, the Select control is designed to handle both with efficiency.
     * Plus, with built-in functions for adding or removing options, it ensures a dynamic user interaction that adapts to various needs.
     * This component use TomSelect library : https://tom-select.js.org/docs/
     */
    interface HTMLIniSelectElement extends Components.IniSelect, HTMLStencilElement {
    }
    var HTMLIniSelectElement: {
        prototype: HTMLIniSelectElement;
        new (): HTMLIniSelectElement;
    };
    /**
     * The Tooltip component acts as a brief informational aide, offering users additional context or guidance when they hover or focus on an element.
     * Subtle yet informative, it unveils insights without disrupting the user flow. Whether elucidating an icon's function,
     * providing supplementary data, or explaining a term, the Tooltip ensures clarity is just a hover away.
     * > The content which must display the tooltip when hovering must be wrapped by `<ini-tooltip>`, can be text, button, any other elements
     * This component use the Popper library : https://popper.js.org/docs/v2/
     */
    interface HTMLIniTooltipElement extends Components.IniTooltip, HTMLStencilElement {
    }
    var HTMLIniTooltipElement: {
        prototype: HTMLIniTooltipElement;
        new (): HTMLIniTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "ini-alert": HTMLIniAlertElement;
        "ini-badge": HTMLIniBadgeElement;
        "ini-button": HTMLIniButtonElement;
        "ini-card": HTMLIniCardElement;
        "ini-date-picker": HTMLIniDatePickerElement;
        "ini-date-range-picker": HTMLIniDateRangePickerElement;
        "ini-dropdown": HTMLIniDropdownElement;
        "ini-input": HTMLIniInputElement;
        "ini-modal": HTMLIniModalElement;
        "ini-select": HTMLIniSelectElement;
        "ini-tooltip": HTMLIniTooltipElement;
    }
}
declare namespace LocalJSX {
    /**
     * The Alert component serves as a dynamic container for conveying vital notifications and messages.
     * Depending on the context, alerts can adopt various types such as Primary, Danger, Success, Warning, and other relevant variants. Each type visually signifies its importance and relevance.
     * Additionally, to enhance clarity and emphasis, alerts can be complemented with a title. For users desiring an uncluttered interface,
     * the alerts also offer a dismissible feature, enabling them to close the message after acknowledgment. Through all its configurations, the Alert component ensures that key communications remain prominent and clear.
     */
    interface IniAlert {
        /**
          * Allows you to hide the alert if the close button is clicked
         */
        "dismissible"?: boolean;
        /**
          * (optional) The title of the alert that accompanies the content
         */
        "headerTitle"?: string;
        /**
          * Context of the alert, if it is an error message: `danger`, an action which is successful: `success` ...
         */
        "variant"?: "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    /**
     * The Badge component is a compact yet powerful means of showcasing status, highlighting states, or drawing attention to specific data points.
     * With its minimalist design, it effortlessly integrates into various UI contexts, making it a go-to for concise visual feedback
     */
    interface IniBadge {
        /**
          * Variant color of badge
         */
        "variant"?: "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    /**
     * The Button component stands as an interactive gateway, inviting users to take action, navigate, or submit.
     * With its versatile design, it can signal importance, set priorities, or provide navigational cues.
     * Whether beckoning a user to 'Learn More', confirming a choice with 'Submit', or pausing a task with 'Cancel', the Button ensures every interaction is clear and intentional.
     */
    interface IniButton {
        "disabled"?: boolean;
        "extraClass"?: string;
        "onIniClick"?: (event: IniButtonCustomEvent<any>) => void;
        "outline"?: boolean;
        "size"?: "small" | "medium" | "large";
        "variant"?: "primary" | "secondary" | "success" | "danger" | "warning" | "info";
    }
    /**
     * The Card component acts as a versatile container, framing content with a clear visual boundary. Whether showcasing snippets of text,
     * hosting other UI components, or spotlighting information with an optional title, the Card offers a neat and structured presentation.
     * It effectively organizes and emphasizes content, ensuring that information stands out in an engaging manner.
     */
    interface IniCard {
        "headerTitle"?: string;
    }
    /**
     * The Date Picker component simplifies the task of selecting dates by providing a user-friendly interface.
     * Whether setting an appointment, scheduling an event, or marking a milestone, it seamlessly integrates into forms and interfaces.
     * With intuitive navigation through days, months, and years, the Date Picker ensures that capturing a specific date or date range is both precise and effortless.
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface IniDatePicker {
        "dateFormat"?: string;
        "disabled"?: boolean;
        "helpText"?: string;
        "label"?: string;
        "name"?: string;
        "placeholder"?: string;
        "value"?: string;
    }
    /**
     * The Date Range Picker component streamlines the process of selecting a span of dates. Ideal for defining periods such as booking intervals,
     * financial quarters, or event durations, it offers an intuitive interface to capture both start and end dates. Its user-centric design ensures
     * that selecting consecutive days or disparate intervals is straightforward, providing clarity and precision in every date range selection.
     * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
     */
    interface IniDateRangePicker {
        "dateFormat"?: string;
        "disabled"?: boolean;
        "endName"?: string;
        "endPlaceholder"?: string;
        "endValue"?: string;
        "helpText"?: string;
        "label"?: string;
        "startName"?: string;
        "startPlaceholder"?: string;
        "startValue"?: string;
    }
    /**
     * The Dropdown component offers a compact way to present multiple options without overwhelming the interface.
     * By clicking or hovering, users can unveil a list of choices, making selections both space-efficient and user-friendly.
     * Whether used for navigation, action lists, or form inputs, the Dropdown ensures a smooth experience, guiding users through their options with elegance and simplicity.
     * This component use the Popper library : https://popper.js.org/docs/v2/
     */
    interface IniDropdown {
        "disabled"?: boolean;
        "label"?: string;
        "outline"?: boolean;
        "placement"?: "top" | "bottom" | "right" | "left";
        "size"?: "small" | "medium" | "large";
    }
    /**
     * Form Input components are the essential touchpoints of user data entry. From simple text fields capturing names to specialized inputs like emails or color pickers,
     * they transform user interactions into actionable data. Designed for clarity and ease of use, these components ensure that users effortlessly provide information,
     * whether its personal details, preferences, or any specific input. Every interaction is optimized for accuracy, ensuring data integrity across varied input types.
     */
    interface IniInput {
        "disabled"?: boolean;
        /**
          * The id value for input and label attributes
         */
        "groupId"?: string;
        "helpText"?: string;
        "inline"?: boolean;
        "label"?: string;
        "name"?: string;
        "placeholder"?: string;
        "prefixIcon"?: string;
        "prefixText"?: string;
        "size"?: "small" | "medium" | "large";
        "suffixIcon"?: string;
        "suffixText"?: string;
        "type"?: "text" | "password" | "email" | "number" | "search" | "tel" | "url" | "color" | "file" | "textarea";
        "value"?: string;
    }
    /**
     * The Modal component emerges as a focused overlay, capturing users' full attention to deliver essential content or actions.
     * Whether presenting vital information, confirming user decisions, or offering supplemental details, the Modal provides an immersive environment, momentarily separating users from the main interface.
     * Its distinct presence ensures that the information or actions within are both central and prioritized, facilitating focused interactions.
     */
    interface IniModal {
        "centerY"?: boolean;
        "closeLabel"?: string;
        "headerTitle"?: string;
        "open"?: boolean;
    }
    /**
     * The Select control offers an intuitive way to present a list of options to users. It allows for easy single or multiple selections from a dropdown menu.
     * Additionally, some select controls provide the ability to search or type in text, offering users an even more streamlined experience.
     * Whether you're choosing from a predefined list or inputting new information, the Select control is designed to handle both with efficiency.
     * Plus, with built-in functions for adding or removing options, it ensures a dynamic user interaction that adapts to various needs.
     * This component use TomSelect library : https://tom-select.js.org/docs/
     */
    interface IniSelect {
        "allowEmpty"?: boolean;
        "disabled"?: boolean;
        "multiple"?: boolean;
        "name"?: string;
        "placeholder"?: string;
        /**
          * Pass the values selected by default (for multiple values must be used a delimiter between the values example: `apple,grape,orange`)
         */
        "selected"?: string;
    }
    /**
     * The Tooltip component acts as a brief informational aide, offering users additional context or guidance when they hover or focus on an element.
     * Subtle yet informative, it unveils insights without disrupting the user flow. Whether elucidating an icon's function,
     * providing supplementary data, or explaining a term, the Tooltip ensures clarity is just a hover away.
     * > The content which must display the tooltip when hovering must be wrapped by `<ini-tooltip>`, can be text, button, any other elements
     * This component use the Popper library : https://popper.js.org/docs/v2/
     */
    interface IniTooltip {
        /**
          * Where should the tooltip be displayed by bringing the element, if the tooltip leaves the parent container, then it will be replaced automatically
         */
        "placement"?: "top" | "bottom" | "right" | "left";
        /**
          * The content to display in the tooltip when hovering
         */
        "titleContent"?: string;
    }
    interface IntrinsicElements {
        "ini-alert": IniAlert;
        "ini-badge": IniBadge;
        "ini-button": IniButton;
        "ini-card": IniCard;
        "ini-date-picker": IniDatePicker;
        "ini-date-range-picker": IniDateRangePicker;
        "ini-dropdown": IniDropdown;
        "ini-input": IniInput;
        "ini-modal": IniModal;
        "ini-select": IniSelect;
        "ini-tooltip": IniTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The Alert component serves as a dynamic container for conveying vital notifications and messages.
             * Depending on the context, alerts can adopt various types such as Primary, Danger, Success, Warning, and other relevant variants. Each type visually signifies its importance and relevance.
             * Additionally, to enhance clarity and emphasis, alerts can be complemented with a title. For users desiring an uncluttered interface,
             * the alerts also offer a dismissible feature, enabling them to close the message after acknowledgment. Through all its configurations, the Alert component ensures that key communications remain prominent and clear.
             */
            "ini-alert": LocalJSX.IniAlert & JSXBase.HTMLAttributes<HTMLIniAlertElement>;
            /**
             * The Badge component is a compact yet powerful means of showcasing status, highlighting states, or drawing attention to specific data points.
             * With its minimalist design, it effortlessly integrates into various UI contexts, making it a go-to for concise visual feedback
             */
            "ini-badge": LocalJSX.IniBadge & JSXBase.HTMLAttributes<HTMLIniBadgeElement>;
            /**
             * The Button component stands as an interactive gateway, inviting users to take action, navigate, or submit.
             * With its versatile design, it can signal importance, set priorities, or provide navigational cues.
             * Whether beckoning a user to 'Learn More', confirming a choice with 'Submit', or pausing a task with 'Cancel', the Button ensures every interaction is clear and intentional.
             */
            "ini-button": LocalJSX.IniButton & JSXBase.HTMLAttributes<HTMLIniButtonElement>;
            /**
             * The Card component acts as a versatile container, framing content with a clear visual boundary. Whether showcasing snippets of text,
             * hosting other UI components, or spotlighting information with an optional title, the Card offers a neat and structured presentation.
             * It effectively organizes and emphasizes content, ensuring that information stands out in an engaging manner.
             */
            "ini-card": LocalJSX.IniCard & JSXBase.HTMLAttributes<HTMLIniCardElement>;
            /**
             * The Date Picker component simplifies the task of selecting dates by providing a user-friendly interface.
             * Whether setting an appointment, scheduling an event, or marking a milestone, it seamlessly integrates into forms and interfaces.
             * With intuitive navigation through days, months, and years, the Date Picker ensures that capturing a specific date or date range is both precise and effortless.
             * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
             */
            "ini-date-picker": LocalJSX.IniDatePicker & JSXBase.HTMLAttributes<HTMLIniDatePickerElement>;
            /**
             * The Date Range Picker component streamlines the process of selecting a span of dates. Ideal for defining periods such as booking intervals,
             * financial quarters, or event durations, it offers an intuitive interface to capture both start and end dates. Its user-centric design ensures
             * that selecting consecutive days or disparate intervals is straightforward, providing clarity and precision in every date range selection.
             * Documentation of used Datepicker : https://mymth.github.io/vanillajs-datepicker
             */
            "ini-date-range-picker": LocalJSX.IniDateRangePicker & JSXBase.HTMLAttributes<HTMLIniDateRangePickerElement>;
            /**
             * The Dropdown component offers a compact way to present multiple options without overwhelming the interface.
             * By clicking or hovering, users can unveil a list of choices, making selections both space-efficient and user-friendly.
             * Whether used for navigation, action lists, or form inputs, the Dropdown ensures a smooth experience, guiding users through their options with elegance and simplicity.
             * This component use the Popper library : https://popper.js.org/docs/v2/
             */
            "ini-dropdown": LocalJSX.IniDropdown & JSXBase.HTMLAttributes<HTMLIniDropdownElement>;
            /**
             * Form Input components are the essential touchpoints of user data entry. From simple text fields capturing names to specialized inputs like emails or color pickers,
             * they transform user interactions into actionable data. Designed for clarity and ease of use, these components ensure that users effortlessly provide information,
             * whether its personal details, preferences, or any specific input. Every interaction is optimized for accuracy, ensuring data integrity across varied input types.
             */
            "ini-input": LocalJSX.IniInput & JSXBase.HTMLAttributes<HTMLIniInputElement>;
            /**
             * The Modal component emerges as a focused overlay, capturing users' full attention to deliver essential content or actions.
             * Whether presenting vital information, confirming user decisions, or offering supplemental details, the Modal provides an immersive environment, momentarily separating users from the main interface.
             * Its distinct presence ensures that the information or actions within are both central and prioritized, facilitating focused interactions.
             */
            "ini-modal": LocalJSX.IniModal & JSXBase.HTMLAttributes<HTMLIniModalElement>;
            /**
             * The Select control offers an intuitive way to present a list of options to users. It allows for easy single or multiple selections from a dropdown menu.
             * Additionally, some select controls provide the ability to search or type in text, offering users an even more streamlined experience.
             * Whether you're choosing from a predefined list or inputting new information, the Select control is designed to handle both with efficiency.
             * Plus, with built-in functions for adding or removing options, it ensures a dynamic user interaction that adapts to various needs.
             * This component use TomSelect library : https://tom-select.js.org/docs/
             */
            "ini-select": LocalJSX.IniSelect & JSXBase.HTMLAttributes<HTMLIniSelectElement>;
            /**
             * The Tooltip component acts as a brief informational aide, offering users additional context or guidance when they hover or focus on an element.
             * Subtle yet informative, it unveils insights without disrupting the user flow. Whether elucidating an icon's function,
             * providing supplementary data, or explaining a term, the Tooltip ensures clarity is just a hover away.
             * > The content which must display the tooltip when hovering must be wrapped by `<ini-tooltip>`, can be text, button, any other elements
             * This component use the Popper library : https://popper.js.org/docs/v2/
             */
            "ini-tooltip": LocalJSX.IniTooltip & JSXBase.HTMLAttributes<HTMLIniTooltipElement>;
        }
    }
}
